version: "3.9"
services:
  to-go:
    build: ./to-go/
    restart: always
    ports: 
      - "4000:3000"
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    restart: always
