version: "3.9"
services:
  backend:
    build: ./backend/
    restart: always
    ports: 
      - "4000:4000"

  frontend:
    build: ./frontend/
    restart: always
    ports:
      - "3000:3000"

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
